import path from "node:path";
import { fileURLToPath } from "node:url";
import { COLORS, addTextBox, createPresentation, exportPresentation, fitPageTitleFontSize, parseCliArgs } from "./pptx_core.mjs";
import { planCorrelationMatrix } from "./plan_correlation_matrix.mjs";
import { loadCorrelationMatrixInput } from "./validate_correlation_matrix.mjs";

const panel = (slide, name, position, fill = COLORS.white, border = COLORS.border) => slide.shapes.add({ name, geometry: "rect", position, fill, line: { style: "solid", fill: border, width: 1 } });
const COEFFICIENT_DARK = "#000000";
function parseHex(color) { return color.replace("#", "").match(/../g).map((value) => parseInt(value, 16)); }
function mix(a, b, t) { const A = parseHex(a); const B = parseHex(b); return `#${A.map((v, i) => Math.round(v + (B[i] - v) * t).toString(16).padStart(2, "0")).join("")}`; }
function relativeLuminance(color) { return parseHex(color).map((value) => value / 255).map((value) => value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4).reduce((sum, value, index) => sum + value * [0.2126, 0.7152, 0.0722][index], 0); }
export function contrastRatio(a, b) { const first = relativeLuminance(a); const second = relativeLuminance(b); return (Math.max(first, second) + 0.05) / (Math.min(first, second) + 0.05); }
export function cellColor(value) { const intensity = Math.min(1, Math.abs(value)); return value < 0 ? mix("#FFFFFF", "#D5634A", intensity) : mix("#FFFFFF", "#2F6B9A", intensity); }
export function coefficientTextColor(value, isDiagonal = false) { if (isDiagonal) return COLORS.text; const fill = cellColor(value); return contrastRatio(COLORS.white, fill) >= contrastRatio(COEFFICIENT_DARK, fill) ? COLORS.white : COEFFICIENT_DARK; }
function signed(value) { return value === 1 ? "1.00" : `${value >= 0 ? "+" : ""}${value.toFixed(2)}`; }
function pairSummary(d) { const pairs = []; for (let i = 0; i < d.metrics.length; i += 1) for (let j = i + 1; j < d.metrics.length; j += 1) pairs.push({ i, j, value: d.matrix[i][j] }); const positive = [...pairs].sort((a, b) => b.value - a.value)[0]; const negative = [...pairs].sort((a, b) => a.value - b.value)[0]; const weak = [...pairs].sort((a, b) => Math.abs(a.value) - Math.abs(b.value))[0]; return [positive, negative, weak]; }

export async function renderCorrelationMatrix(data, output = {}) {
  const plan = planCorrelationMatrix(data); const d = plan.normalized.diagram; const { presentation, slide } = createPresentation(output.background);
  addTextBox(slide, { name: "page-title", text: plan.title.text, position: plan.title, fontSize: fitPageTitleFontSize(plan.title.text), bold: true, color: COLORS.navy, maxLines: 2 });
  if (plan.subtitle) addTextBox(slide, { name: "page-subtitle", text: plan.subtitle.text, position: plan.subtitle, fontSize: 16, color: COLORS.muted, maxLines: 1 });
  panel(slide, "correlation-frame", plan.matrix);
  const { cellHeight, cellWidth, labelWidth, left, top } = plan.grid;
  addTextBox(slide, { name: "matrix-caption", text: `${d.method === "pearson" ? "Pearson" : "Spearman"} 系数`, position: { left: plan.matrix.left + 14, top: plan.matrix.top + 8, width: 116, height: 24 }, fontSize: 12, bold: true, color: COLORS.navy, singleLine: true });
  d.metrics.forEach((metric, i) => { addTextBox(slide, { name: `column-label-${i + 1}`, text: metric.label.text, position: { left: left + i * cellWidth, top: top - 34, width: cellWidth, height: 30 }, fontSize: 12, bold: true, color: COLORS.text, alignment: "center", singleLine: true }); addTextBox(slide, { name: `row-label-${i + 1}`, text: metric.label.text, position: { left: plan.matrix.left + 10, top: top + i * cellHeight, width: labelWidth - 18, height: cellHeight }, fontSize: 14, bold: true, color: COLORS.text, alignment: "right", singleLine: true }); });
  d.matrix.forEach((row, i) => row.forEach((value, j) => { const diagonal = i === j; const fill = diagonal ? COLORS.soft : cellColor(value); panel(slide, `cell-${i + 1}-${j + 1}`, { left: left + j * cellWidth, top: top + i * cellHeight, width: cellWidth, height: cellHeight }, fill, COLORS.white); addTextBox(slide, { name: `coefficient-${i + 1}-${j + 1}`, text: signed(value), position: { left: left + j * cellWidth + 2, top: top + i * cellHeight + 1, width: cellWidth - 4, height: cellHeight - 2 }, fontSize: 12, bold: Math.abs(value) >= d.display_threshold, color: coefficientTextColor(value, diagonal), alignment: "center", singleLine: true }); }));
  panel(slide, "candidate-rail", plan.rail, COLORS.soft); addTextBox(slide, { name: "candidate-title", text: "优先核查的变量关系", position: { left: plan.rail.left + 16, top: plan.rail.top + 16, width: plan.rail.width - 32, height: 28 }, fontSize: 18, bold: true, color: COLORS.navy, singleLine: true });
  const labels = ["最强正相关", "最强负相关", "最弱关系"]; pairSummary(d).forEach((pair, index) => { const y = plan.rail.top + 70 + index * 112; const color = index === 1 ? "#B84B35" : index === 0 ? COLORS.blue : COLORS.muted; const valueWidth = 96; const kindWidth = 112; const pairLeft = plan.rail.left + 16 + kindWidth + 10; const pairWidth = plan.rail.width - 32 - kindWidth - 10 - valueWidth - 8; addTextBox(slide, { name: `pair-kind-${index + 1}`, text: labels[index], position: { left: plan.rail.left + 16, top: y, width: kindWidth, height: 24 }, fontSize: 14, bold: true, color, singleLine: true }); addTextBox(slide, { name: `pair-label-${index + 1}`, text: `${d.metrics[pair.i].label.text} × ${d.metrics[pair.j].label.text}`, position: { left: pairLeft, top: y - 2, width: pairWidth, height: 48 }, fontSize: 16, bold: index < 2, color: COLORS.text, maxLines: 2 }); addTextBox(slide, { name: `pair-value-${index + 1}`, text: signed(pair.value), position: { left: plan.rail.left + plan.rail.width - 16 - valueWidth, top: y - 3, width: valueWidth, height: 28 }, fontSize: 18, bold: true, color, alignment: "right", singleLine: true }); });
  addTextBox(slide, { name: "threshold-note", text: `重点阈值：|r| ≥ ${d.display_threshold.toFixed(2)}；弱关系按 |r| 最小识别`, position: { left: plan.rail.left + 16, top: plan.rail.top + plan.rail.height - 50, width: plan.rail.width - 32, height: 34 }, fontSize: 12, color: COLORS.muted, maxLines: 2 });
  if (d.conclusion) addTextBox(slide, { name: "correlation-conclusion", text: d.conclusion.text, position: { left: plan.footer.left, top: plan.footer.top - 2, width: plan.footer.width, height: 22 }, fontSize: 14, bold: true, color: COLORS.navy, maxLines: 1 });
  const footer1 = `${d.period.text}；${d.population.text}；n=${d.sample_size}；缺失值：${d.missing_value_handling.text}`; addTextBox(slide, { name: "method-note", text: footer1, position: { left: plan.footer.left, top: plan.footer.top + 20, width: plan.footer.width, height: 20 }, fontSize: 12, color: COLORS.muted, maxLines: 1 });
  addTextBox(slide, { name: "source-note", text: `${d.source_note.text}；${d.causality_note.text}`, position: { left: plan.footer.left, top: plan.footer.top + 40, width: plan.footer.width, height: 20 }, fontSize: 12, color: COLORS.muted, maxLines: 1 });
  if (d.disclosure) addTextBox(slide, { name: "synthetic-disclosure", text: d.disclosure.text, position: { left: plan.footer.left, top: plan.footer.top + 60, width: plan.footer.width, height: 18 }, fontSize: 12, bold: true, color: COLORS.orange, maxLines: 1 });
  await exportPresentation(presentation, output); return plan;
}
async function main() { const options = parseCliArgs(process.argv.slice(2)); const data = await loadCorrelationMatrixInput(options.input); const plan = await renderCorrelationMatrix(data, options); process.stdout.write(`${JSON.stringify({ ok: true, module: data.module_id, slide: plan.slide })}\n`); }
if (process.argv[1] && path.basename(process.argv[1]) === path.basename(fileURLToPath(import.meta.url))) main().catch((error) => { process.stderr.write(`${JSON.stringify({ code: error.code ?? "RENDER_FAIL", message: error.message })}\n`); process.exitCode = 1; });
